site_name: Today I Learned
repo_name: tighug/til
repo_url: https://github.com/tighug/til.git
copyright: © 2022 tighug
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: green
  features:
    - navigation.tabs
    - navigation.instant
  language: ja
  custom_dir: overrides
plugins:
  - search
  - git-revision-date-localized:
      type: iso_date
extra:
  search:
    language: ja
extra_css:
  - extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
nav:
  - README: index.md
  - Basic:
      - Common: Basic/index.md
      - Linux Directory: Basic/linux-directory.md
      - Unix Command: Basic/unix-command.md
      - Visual Studio Code: Basic/vscode.md
      - Terminal:
          - bat: Basic/Terminal/bat.md
          - exa: Basic/Terminal/exa.md
          - fish: Basic/Terminal/fish.md
          - Starship: Basic/Terminal/starship.md
      - Git:
          - Git: Basic/Git/index.md
          - Commit Guidline: Basic/Git/commit-guidline.md
          - GitHub Actions: Basic/Git/github-actions.md
          - GitHub: Basic/Git/github.md
  - Frontend:
      - Frontend: Frontend/index.md
      - Atomic Design: Frontend/atomic-design.md
      - Test:
          - テスト: Frontend/Test/index.md
          - Cypress: Frontend/Test/cypress.md
          - Jest Styled Components: Frontend/Test/jest-styled-components.md
          - Jest: Frontend/Test/jest.md
          - Mock Service Worker: Frontend/Test/msw.md
          - ts-jest: Frontend/Test/ts-jest.md
          - testing-library:
              - Testing Library: Frontend/Test/testing-library/index.md
              - jest-dom: Frontend/Test/testing-library/jest-dom.md
              - React Testing Library: Frontend/Test/testing-library/react.md
              - user-event: Frontend/Test/testing-library/user-event.md
      - Util:
          - Chromatic: Frontend/Util/chromatic.md
          - Husky: Frontend/Util/husky.md
          - lint-staged: Frontend/Util/lint-staged.md
          - semantic-release: Frontend/Util/semantic-release.md
          - Storybook Deployer: Frontend/Util/storybook-deployer.md
          - Storybook: Frontend/Util/storybook.md
      - CSS:
          - CSS: Frontend/CSS/index.md
          - CSS Flexbox: Frontend/CSS/flex-box.md
          - Learning Resources: Frontend/CSS/learning-resources.md
          - CSS Property Order: Frontend/CSS/property-order.md
          - stylelint: Frontend/CSS/stylelint.md
      - Vue:
          - Nuxt.js: Frontend/Vue/nuxt.md
          - Vue.js: Frontend/Vue/vue.md
          - Vuex: Frontend/Vue/vuex.md
      - HTML:
          - HTML: Frontend/HTML/index.md
          - Learning Resources: Frontend/HTML/learning-resources.md
          - Semantic HTML: Frontend/HTML/semantic-html.md
      - JavaScript:
          - JavaScript: Frontend/JavaScript/index.md
          - Babel: Frontend/JavaScript/babel.md
          - ESLint: Frontend/JavaScript/eslint.md
          - Node.js: Frontend/JavaScript/nodejs.md
          - npm: Frontend/JavaScript/npm.md
          - Prettier: Frontend/JavaScript/prettier.md
          - Yarn: Frontend/JavaScript/yarn.md
          - TypeScript:
              - TypeScript: Frontend/JavaScript/TypeScript/index.md
              - ts-node: Frontend/JavaScript/TypeScript/ts-node.md
          - Webpack:
              - Webpack Dev Server: Frontend/JavaScript/Webpack/WebpackDevServer.md
              - webpack: Frontend/JavaScript/Webpack/webpack.md
      - Electron:
          - Electron: Frontend/Electron/index.md
          - electron-builder: Frontend/Electron/electron-builder.md
          - electron-webpack: Frontend/Electron/electron-webpack.md
      - React:
          - React: Frontend/React/index.md
          - React Context: Frontend/React/react-context.md
          - React Hooks: Frontend/React/react-hooks.md
          - React Hot Loader: Frontend/React/react-hot-loader.md
          - React Redux: Frontend/React/react-redux.md
          - React Router: Frontend/React/react-router.md
          - Redux Toolkit: Frontend/React/redux-toolkit.md
          - Redux: Frontend/React/redux.md
          - Styled Components: Frontend/React/styled-components.md
          - Styled System: Frontend/React/styled-system.md
      - ReactNative:
          - React Native: Frontend/ReactNative/index.md
          - Expo: Frontend/ReactNative/expo.md
  - Backend:
      - Backend: Backend/index.md
      - Restful API: Backend/restful-api.md
      - Nodejs:
          - Node.js: Backend/Nodejs/index.md
          - Configuration:
              - dotenv: Backend/Nodejs/Configuration/dotenv.md
          - Standard Library:
              - fs: Backend/Nodejs/Standard Library/fs.md
              - path: Backend/Nodejs/Standard Library/path.md
          - TypeScript:
              - TypeScript: Backend/Nodejs/TypeScript/index.md
              - Babel: Backend/Nodejs/TypeScript/babel.md
              - ts-node-dev: Backend/Nodejs/TypeScript/ts-node-dev.md
              - ts-node: Backend/Nodejs/TypeScript/ts-node.md
          - Linting&Formatting:
              - ESLint: Backend/Nodejs/Linting&Formatting/eslint.md
              - Husky: Backend/Nodejs/Linting&Formatting/husky.md
              - lint-staged: Backend/Nodejs/Linting&Formatting/lint-staged.md
              - Prettier: Backend/Nodejs/Linting&Formatting/prettier.md
              - textlint: Backend/Nodejs/Linting&Formatting/textlint.md
          - DB:
              - better-sqlite3: Backend/Nodejs/DB/better-sqlite3.md
              - db-migrate: Backend/Nodejs/DB/db-migrate.md
              - mysql2: Backend/Nodejs/DB/mysql2.md
              - Prisma: Backend/Nodejs/DB/prisma.md
              - Sequelize: Backend/Nodejs/DB/sequelize.md
              - TypeORM: Backend/Nodejs/DB/typeorm.md
          - Error:
              - http-errors: Backend/Nodejs/Error/http-errors.md
          - Validation:
              - express-validator: Backend/Nodejs/Validation/express-validator.md
              - validator: Backend/Nodejs/Validation/validator.md
      - Go:
          - Go: Backend/Go/index.md
          - Afero: Backend/Go/afero.md
          - Cobra: Backend/Go/cobra.md
          - Echo: Backend/Go/echo.md
          - Go encoding/csv: Backend/Go/encoding-csv.md
          - GoReleaser: Backend/Go/go-releaser.md
          - GORM: Backend/Go/gorm.md
          - jwt-go: Backend/Go/jwt-go.md
          - Go Project Layout: Backend/Go/project-layout.md
          - Viper: Backend/Go/viper.md
          - zerolog: Backend/Go/zerolog.md
          - standard:
              - Go bufio: Backend/Go/standard/bufio.md
              - Go io/ioutil: Backend/Go/standard/io-ioutil.md
              - Go os/exec: Backend/Go/standard/os-exec.md
              - Go os: Backend/Go/standard/os.md
      - Python:
          - Flask: Backend/Python/flask.md
      - DB:
          - DB Design: Backend/DB/DBDesign.md
          - MySQL: Backend/DB/mysql.md
  - DevOps:
      - DevOps: DevOps/index.md
      - Make: DevOps/make.md
      - Nginx: DevOps/nginx.md
      - Docker:
          - Docker: DevOps/Docker/index.md
          - Compose: DevOps/Docker/compose.md
          - Dockerfile: DevOps/Docker/file.md
          - hadolint: DevOps/Docker/hadolint.md
          - Kubernetes: DevOps/Docker/kubernetes.md
      - AWS:
          - AWS: DevOps/AWS/index.md
          - Analytics: DevOps/AWS/analytics.md
          - Compute: DevOps/AWS/compute.md
          - Container: DevOps/AWS/container.md
          - Cost Management: DevOps/AWS/cost-management.md
          - Database: DevOps/AWS/database.md
          - Application Integration: DevOps/AWS/integration.md
          - Management & Governance: DevOps/AWS/management.md
          - Migration: DevOps/AWS/migration.md
          - Network: DevOps/AWS/network.md
          - Secutity: DevOps/AWS/security.md
          - Storage: DevOps/AWS/storage.md
          - Design Pattern:
              - Design Pattern: DevOps/AWS/Design Pattern/index.md
  - Software Design:
      - Software Design: Software Design/index.md
      - Class Diagram: Software Design/class-diagram.md
      - Clean Architecture: Software Design/clean-architecture.md
      - Clean Code: Software Design/clean-code.md
      - ドメイン駆動設計: Software Design/ddd.md
      - Design Patterns: Software Design/design-patterns.md
      - Design Principles: Software Design/design-principles.md
      - Object-Oriented Programming: Software Design/oop.md
      - Programming Paradigms: Software Design/paradigms.md
      - SOLID: Software Design/solid.md
  - Data Science:
      - Machine Learning: Data Science/index.md
      - Hugging Face Transformers:
          - Hugging Face Transformers: Data Science/Hugging Face Transformers/index.md
      - Python:
          - Python: Data Science/Python/index.md
          - Beautiful Soup: Data Science/Python/beautiful-soup.md
          - FastAPI: Data Science/Python/fast-api.md
          - Loguru: Data Science/Python/loguru.md
          - Matplotlib: Data Science/Python/matplotlib.md
          - Mypy: Data Science/Python/mypy.md
          - NumPy: Data Science/Python/numpy.md
          - Poetry: Data Science/Python/poetry.md
          - pyenv: Data Science/Python/pyenv.md
          - python-dotenv: Data Science/Python/python-dotenv.md
          - Requests: Data Science/Python/requests.md
          - Scrapy: Data Science/Python/scrapy.md
          - tqdm: Data Science/Python/tqdm.md
          - Uvicorn: Data Science/Python/uvicorn.md
          - Lingting&Formatting:
              - black: Data Science/Python/Lingting&Formatting/black.md
              - flake8: Data Science/Python/Lingting&Formatting/flake8.md
          - Standard Library:
              - pathlib: Data Science/Python/Standard Library/pathlib.md
      - PyTorch:
          - PyTorch: Data Science/PyTorch/index.md
          - PyTorch Lightning: Data Science/PyTorch/PyTorch Lightning.md
          - torchvision:
              - torchvision: Data Science/PyTorch/torchvision/index.md
          - torchtext:
              - Torchtext: Data Science/PyTorch/torchtext/index.md
              - Datasets: Data Science/PyTorch/torchtext/datasets.md
  - Blockchain:
      - Blockchain: Blockchain/index.md
      - IWA: Blockchain/IWA.md
      - Oracle: Blockchain/Oracle.md
      - TTF: Blockchain/TTF.md
      - Truffle: Blockchain/Truffle.md
      - web3.js: Blockchain/web3js.md
      - Solidity:
          - Solidity: Blockchain/Solidity/index.md
          - Solidity Common Patterns: Blockchain/Solidity/CommonPatterns.md
          - Solidity Security: Blockchain/Solidity/Security.md
          - Solidity Usage: Blockchain/Solidity/Usage.md
          - stringutils: Blockchain/Solidity/stringutils.md
      - OpenZeppelin:
          - OpenZeppelin: Blockchain/OpenZeppelin/index.md
          - ERC 20: Blockchain/OpenZeppelin/ERC20.md
          - ERC 721: Blockchain/OpenZeppelin/ERC721.md
          - ERC 777: Blockchain/OpenZeppelin/ERC777.md
          - Ownable: Blockchain/OpenZeppelin/Ownership.md
