site_name: Today I Learned
repo_name: tighug/til
repo_url: https://github.com/tighug/til.git
copyright: © 2022 tighug
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  features:
    - navigation.tabs
    - navigation.instant
  language: ja
extra:
  search:
    language: ja
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
nav:
  - Home: index.md
  - App Dev:
      - Idea: App Dev/idea.md
      - Meleon UI: App Dev/meleon-ui.md
      - Meleon: App Dev/meleon.md
      - Personal AI: App Dev/personal-ai.md
  - Back-end:
      - Restful API: Back-end/restful-api.md
      - DB:
          - DB Design: Back-end/DB/DBDesign.md
          - MySQL: Back-end/DB/mysql.md
      - Go:
          - Go: Back-end/Go/index.md
          - Afero: Back-end/Go/afero.md
          - Cobra: Back-end/Go/cobra.md
          - Echo: Back-end/Go/echo.md
          - Go encoding/csv: Back-end/Go/encoding-csv.md
          - GoReleaser: Back-end/Go/go-releaser.md
          - GORM: Back-end/Go/gorm.md
          - Go Project Layout: Back-end/Go/project-layout.md
          - Viper: Back-end/Go/viper.md
          - zerolog: Back-end/Go/zerolog.md
          - standard:
              - Go bufio: Back-end/Go/standard/bufio.md
              - Go io/ioutil: Back-end/Go/standard/io-ioutil.md
              - Go os/exec: Back-end/Go/standard/os-exec.md
              - Go os: Back-end/Go/standard/os.md
      - Java:
          - Java: Back-end/Java/index.md
      - Python:
          - Flask: Back-end/Python/flask.md
  - Blockchain:
      - Blockchain: Blockchain/README.md
      - IWA: Blockchain/IWA.md
      - Oracle: Blockchain/Oracle.md
      - TTF: Blockchain/TTF.md
      - Truffle: Blockchain/Truffle.md
      - web3.js: Blockchain/web3js.md
      - open-zeppelin:
          - OpenZeppelin: Blockchain/open-zeppelin/OpenZeppelin.md
          - ERC 20: Blockchain/open-zeppelin/OpenZeppelin_ERC20.md
          - ERC 721: Blockchain/open-zeppelin/OpenZeppelin_ERC721.md
          - ERC 777: Blockchain/open-zeppelin/OpenZeppelin_ERC777.md
          - Ownable: Blockchain/open-zeppelin/OpenZeppelin_Ownership.md
      - solidity:
          - Solidity: Blockchain/solidity/Solidity.md
          - Solidity Common Patterns: Blockchain/solidity/Solidity_CommonPatterns.md
          - Solidity Security: Blockchain/solidity/Solidity_Security.md
          - Solidity Usage: Blockchain/solidity/Solidity_Usage.md
          - stringutils: Blockchain/solidity/Solidity_stringutils.md
  - Book:
      - ゼロから作る Deep Learning 1: Book/ゼロから作るDeepLearning1.md
      - ゼロから作る Deep Learning 2: Book/ゼロから作るDeepLearning2.md
      - 基本情報技術者教室:
          - 1. コンピュータ構成要素: Book/基本情報技術者教室/1-コンピュータ構成要素.md
          - 10. マネジメント系: Book/基本情報技術者教室/10-マネジメント系.md
          - 11. ストラテジ系: Book/基本情報技術者教室/11-ストラテジ系.md
          - 2. ソフトウェアとマルチメディア: Book/基本情報技術者教室/2-ソフトウェアとマルチメディア.md
          - 3. 基礎理論: Book/基本情報技術者教室/3-基礎理論.md
          - 4. アルゴリズムとプログラミング: Book/基本情報技術者教室/4-アルゴリズムとプログラミング.md
          - 5. システム構成要素: Book/基本情報技術者教室/5-システム構成要素.md
          - 6. データベース技術: Book/基本情報技術者教室/6-データベース技術.md
          - 7. ネットワーク技術: Book/基本情報技術者教室/7-ネットワーク技術.md
          - 8. 情報セキュリティ: Book/基本情報技術者教室/8-情報セキュリティ.md
          - 9. システム開発技術: Book/基本情報技術者教室/9-システム開発技術.md
  - Common:
      - Common: Common/index.md
      - Make: Common/make.md
      - VSCode: Common/vscode.md
      - Git:
          - Git Commit Guidline: Common/Git/git-commit-guidline.md
          - git-flow: Common/Git/git-flow.md
          - Git: Common/Git/git.md
          - GitHub Actions: Common/Git/github-actions.md
          - GitHub: Common/Git/github.md
      - Office:
          - Excel: Common/Office/excel.md
      - Terminal:
          - bat: Common/Terminal/bat.md
          - exa: Common/Terminal/exa.md
          - fish: Common/Terminal/fish.md
          - Linux: Common/Terminal/linux.md
          - Starship: Common/Terminal/starship.md
  - Front-end:
      - Atomic Design: Front-end/atomic-design.md
      - css:
          - CSS: Front-end/css/index.md
          - CSS: Front-end/css/css.md
          - CSS Flexbox: Front-end/css/flex-box.md
          - Learning Resources: Front-end/css/learning-resources.md
          - CSS Property Order: Front-end/css/property-order.md
          - stylelint: Front-end/css/stylelint.md
      - electron:
          - Electron: Front-end/electron/index.md
          - electron-builder: Front-end/electron/electron-builder.md
          - electron-webpack: Front-end/electron/electron-webpack.md
      - html:
          - HTML: Front-end/html/index.md
          - Learning Resources: Front-end/html/learning-resources.md
          - Semantic HTML: Front-end/html/semantic-html.md
      - javascript:
          - JavaScript: Front-end/javascript/index.md
          - Babel: Front-end/javascript/babel.md
          - ESLint: Front-end/javascript/eslint.md
          - Node.js: Front-end/javascript/nodejs.md
          - npm: Front-end/javascript/npm.md
          - Prettier: Front-end/javascript/prettier.md
          - Yarn: Front-end/javascript/yarn.md
          - typescript:
              - TypeScript: Front-end/javascript/typescript/index.md
              - ts-node: Front-end/javascript/typescript/ts-node.md
          - webpack:
              - Webpack Dev Server: Front-end/javascript/webpack/WebpackDevServer.md
              - webpack: Front-end/javascript/webpack/webpack.md
      - react:
          - React: Front-end/react/index.md
          - React Context: Front-end/react/react-context.md
          - React Hooks: Front-end/react/react-hooks.md
          - React Hot Loader: Front-end/react/react-hot-loader.md
          - React Redux: Front-end/react/react-redux.md
          - React Router: Front-end/react/react-router.md
          - Redux Toolkit: Front-end/react/redux-toolkit.md
          - Redux: Front-end/react/redux.md
          - Styled Components: Front-end/react/styled-components.md
          - Styled System: Front-end/react/styled-system.md
      - test:
          - テスト: Front-end/test/index.md
          - Cypress: Front-end/test/cypress.md
          - Jest Styled Components: Front-end/test/jest-styled-components.md
          - Jest: Front-end/test/jest.md
          - Mock Service Worker: Front-end/test/msw.md
          - ts-jest: Front-end/test/ts-jest.md
          - testing-library:
              - Testing Library: Front-end/test/testing-library/index.md
              - jest-dom: Front-end/test/testing-library/jest-dom.md
              - React Testing Library: Front-end/test/testing-library/react.md
              - user-event: Front-end/test/testing-library/user-event.md
      - util:
          - Chromatic: Front-end/util/chromatic.md
          - Husky: Front-end/util/husky.md
          - lint-staged: Front-end/util/lint-staged.md
          - semantic-release: Front-end/util/semantic-release.md
          - Storybook Deployer: Front-end/util/storybook-deployer.md
          - Storybook: Front-end/util/storybook.md
      - vue:
          - Nuxt.js: Front-end/vue/nuxt.md
          - Vue.js: Front-end/vue/vue.md
          - Vuex: Front-end/vue/vuex.md
  - Machine Learning:
      - Machine Learning: Machine Learning/index.md
      - CNN: Machine Learning/cnn.md
      - RNN: Machine Learning/rnn.md
      - Python:
          - Python: Machine Learning/Python/index.md
          - Beautiful Soup: Machine Learning/Python/beautiful-soup.md
          - black: Machine Learning/Python/black.md
          - flake8: Machine Learning/Python/flake8.md
          - Loguru: Machine Learning/Python/loguru.md
          - Matplotlib: Machine Learning/Python/matplotlib.md
          - Mypy: Machine Learning/Python/mypy.md
          - NumPy: Machine Learning/Python/numpy.md
          - poetry: Machine Learning/Python/poetry.md
          - pyenv: Machine Learning/Python/pyenv.md
          - python-dotenv: Machine Learning/Python/python-dotenv.md
          - PyTorch: Machine Learning/Python/pytorch.md
          - Scrapy: Machine Learning/Python/scrapy.md
          - tqdm: Machine Learning/Python/tqdm.md
          - Standard Library:
              - pathlib: Machine Learning/Python/Standard Library/pathlib.md
  - Software Design:
      - Software Design: Software Design/index.md
      - Class Diagram: Software Design/class-diagram.md
      - Clean Architecture: Software Design/clean-architecture.md
      - Clean Code: Software Design/clean-code.md
      - ドメイン駆動設計: Software Design/ddd.md
      - Design Patterns: Software Design/design-patterns.md
      - Design Principles: Software Design/design-principles.md
      - Object-Oriented Programming: Software Design/oop.md
      - Programming Paradigms: Software Design/paradigms.md
      - SOLID: Software Design/solid.md
